# config file for running 10x pipeline 

DATA:
    "../runs/20170623_zeemans"

PROJECT:
    "zemans"

TRANSCRIPTOME:
    "/vol3/home/riemondy/Projects/shared_dbases/cell_ranger/refdata-cellranger-mm10-1.2.0"

SAMPLES:
    - 3161-ATII-1
    - 3161-ATII-2
    - 3161-ATII-3
    - 3162-ATII-5
    - 3162-ATTII-4

EXPT_GROUPS:
    - 3161-ATII-1,3161-ATII-2,3161-ATII-3,3162-ATII-5,3162-ATTII-4
