---
title: "CCA analysis"
author: "Kent Riemondy RBI"
date: "9/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Compare naive to injured AT II cells 

```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source("../R/globals.R")
processed_data_dir <- file.path(results_dir, "preprocess")

main_outdir <- "revision"
dir.create(main_outdir, showWarnings = FALSE)
```

```{r load_dat}
atcells <- readRDS(file.path(processed_data_dir, "s_obj_final.rds"))
atcells <- SetAllIdent(atcells, "res.0.6")
```

Split naive and injured type II into two seurats and attempt to align.


```{r}
naive_cells <- rownames(atcells@meta.data)[atcells@meta.data$labeled_clusters == "Naive Type II"]
inj_cells <- rownames(atcells@meta.data)[atcells@meta.data$labeled_clusters == "Injured Type II"]

naive_obj <- SubsetData(atcells, cells.use = naive_cells)
inj_obj <- SubsetData(atcells, cells.use = inj_cells)
```

```{r}
# Set up naive object
naive_obj <- NormalizeData(naive_obj)
naive_obj <- ScaleData(naive_obj, 
                       vars.to.regress = c("nUMI", "proportion.mito"))

# Set up injured object
inj_obj <- NormalizeData(inj_obj)
inj_obj <- ScaleData(inj_obj, 
                       vars.to.regress = c("nUMI", "proportion.mito"))

# Gene selection for input to CCA
naive_obj <- FindVariableGenes(naive_obj, do.plot = T)
inj_obj <- FindVariableGenes(inj_obj, y.cutoff = 0.75,
                             do.plot = T)
length(naive_obj@var.genes)
length(inj_obj@var.genes)
  
g.1 <- head(rownames(naive_obj@hvg.info), 1500)
g.2 <- head(rownames(inj_obj@hvg.info), 1500)
genes.use <- unique(c(g.1, g.2))
genes.use <- intersect(genes.use, rownames(naive_obj@scale.data))
genes.use <- intersect(genes.use, rownames(inj_obj@scale.data))
length(genes.use)
```

```{r cca}

naive_obj@meta.data$treatment <- "control"
inj_obj@meta.data$treatment <- "lps"
comb_obj <- RunCCA(naive_obj, 
                          inj_obj, 
                          genes.use = genes.use, num.cc = 20)


p1 <- DimPlot(comb_obj, reduction.use = "cca", group.by = "treatment", 
    pt.size = 0.5, do.return = TRUE)
p2 <- VlnPlot(comb_obj, features.plot = "CC1", group.by = "treatment", 
    do.return = TRUE)
plot_grid(p1, p2)
```

```{r}

PrintDim(object = comb_obj, reduction.type = "cca", dims.print = 1:5, 
    genes.print = 10)
DimHeatmap(object = comb_obj, reduction.type = "cca", cells.use = 500, 
    dim.use = 1:9, do.balanced = TRUE)
```

```{r}

comb_obj <- AlignSubspace(comb_obj, reduction.type = "cca", grouping.var = "treatment", 
    dims.align = 1:20)

comb_obj <- RunTSNE(comb_obj, reduction.use = "cca.aligned", dims.use = 1:20, 
    do.fast = T)

comb_obj <- FindClusters(comb_obj, reduction.type = "cca.aligned", 
    resolution = 0.6, dims.use = 1:20)

p1 <- TSNEPlot(comb_obj, 
               do.return = T, cells.use = naive_cells,
               pt.size = 0.5, group.by = "treatment")

p2 <- TSNEPlot(comb_obj, 
               do.return = T, cells.use = inj_cells,
               pt.size = 0.5, group.by = "treatment")
p3 <- TSNEPlot(comb_obj, 
               do.return = T, 
               pt.size = 0.5, group.by = "treatment")
p4 <- TSNEPlot(comb_obj, do.label = T, do.return = T, pt.size = 0.5)
plt <- plot_grid(p1, p2, p3, p4)

plt

plt <- plot_feature(comb_obj, 
             "treatment", 
             pt_size = 0.01, 
             .cols = brewer.pal(3, "Set1"), 
             pt_alpha = 0.75) 

save_plot(file.path("revision", "new_figures", "cca_analysis.pdf"), plt, 
          base_aspect_ratio = 1.3)

dir.create("cca")
saveRDS(comb_obj, "cca/cca_obj.rds")
```


```{r}

cca_obj <- readRDS("cca/cca_obj.rds")

# get naive type II markers
marker_genes <- read_tsv("markers/naive_cell_types_markers_wilcox.txt") %>% 
  filter(cluster == "Naive Type II") %>% 
  pull(gene) %>% 
  unique()

# modify VizDimReduction to return tidy data for ggplotting
top_dim_genes <- function(object, reduction.type = "pca", dims.use = 1:5, num.genes = 30, 
    use.full = FALSE, font.size = 0.5, nCol = NULL, do.balanced = FALSE) 
{
    if (use.full) {
        dim.scores <- GetDimReduction(object = object, reduction.type = reduction.type, 
            slot = "gene.loadings.full")
    } else {
        dim.scores <- GetDimReduction(object = object, reduction.type = reduction.type, 
            slot = "gene.loadings")
    }
    if (is.null(x = nCol)) {
        if (length(x = dims.use) > 6) {
            nCol <- 3
        }
        else if (length(x = dims.use) > 9) {
            nCol <- 4
        }
        else {
            nCol <- 2
        }
    }
    num.row <- floor(x = length(x = dims.use)/nCol - 1e-05) +     1
    reduction.name <- toupper(reduction.type)
    par(mfrow = c(num.row, nCol))
    out <- list()
    for (i in dims.use) {
        subset.use <- dim.scores[DimTopGenes(object = object, 
            dim.use = i, reduction.type = reduction.type, num.genes = num.genes, 
            use.full = use.full, do.balanced = do.balanced), 
            ]
        out[[i]] <- subset.use[, i, drop = F]
        colnames(out[[i]]) <- "value"
        names(out)[i] <- paste0(reduction.name, i)
    }
    map_dfr(out, ~as.data.frame(.x) %>% 
              tibble::rownames_to_column("gene"), 
            .id = "dimension")
}



plt_dat <- top_dim_genes(cca_obj, 
                         reduction.type = "cca", 
                         num.genes = 50, 
                         dims.use = 1:3, 
                         do.balanced = T) %>% 
  mutate(marker = ifelse(gene %in% marker_genes,
                         "AEC2 marker",
                         "other gene")) %>% 
  group_by(dimension) %>% 
  arrange(value, .by_group = T)

plts <- map( unique(plt_dat$dimension), 
     function(d){
  res <- filter(plt_dat, dimension == d) 
  res$gene <- factor(res$gene, levels = res$gene[order(res$value)])
  markers <- res$marker[order(res$value)]
  label_cols <- ifelse(markers == "AEC2 marker",
         brewer.pal(3, "Set1")[1],
         "black")
  ggplot(res, aes(value, gene)) +
  geom_point(aes(color = marker)) + 
  scale_color_brewer(palette = "Set1", name = "") +
  labs(x = d, y = "")  +
  guides(color = guide_legend(override.aes = list(size = 4),
         nrow = 2)) +
  theme(legend.pos = "top",
        axis.text.y = element_text(color = label_cols)) 
})

plt <- plot_grid(plotlist = plts, nrow = 1, ncol = 3)

save_plot(file.path("revision", "new_figures", "cca_analysis_top_genes.pdf"),
          plt, nrow = 1, ncol = 3, base_aspect_ratio = 0.33, base_height = 8)
```